spring:
  application:
    name: order
  #thymeleaf 配置
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates
    cache: false
#服务注册中心地址（刚刚搭建的Eureka Server的地址）
eureka:
  client:
    #是否向服务中心注册自己
    register-with-eureka: true
    #设置eureka服务中心的地址
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#设置自己启动的端口,默认8080
server:
  port: 8763




